global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: apiservices
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'prometheus:9090'
        - 'apiservice1:6969'
        - 'apiservice2:6969'
        - 'apiservice299999:6969'

remote_write:
  - url: https://prometheus-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: 793196
      password: eyJrIjoiZGZhYTNmN2I5ZWU2MmZhODQzN2M4MmI4ODg0ZTI1MDgwYjdmZjBiNCIsIm4iOiJhbm90aGVyb25lIiwiaWQiOjgwMzEyN30=